DROP TABLE IF EXISTS customer CASCADE;

DROP TABLE IF EXISTS score ;

DROP TABLE IF EXISTS application ;



CREATE TABLE customer(
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         national_id VARCHAR(11) NOT NULL UNIQUE,
                         name VARCHAR(25) NOT NULL,
                         surname VARCHAR(25) NOT NULL,
                         monthly_income INT NOT NULL,
                         phone_number VARCHAR(11) NOT NULL UNIQUE,
                         credit_score INT ,
                         credit_result  VARCHAR(15),
                         credit_limit INT

);










--//////Sample Static Test Values//////

INSERT INTO customer(national_id, name, surname, monthly_income, phone_number,credit_score,credit_result,credit_limit)
VALUES
       ('21432561238','Mehmet','Yılmaz',5000,'05415629876',800,'CONFIRMED',10000),
       ('14582736512','Ali','Yılmaz',10000,'05448723450',1000,'CONFIRMED',40000),
       ('28375828134','Berk','Balcı',3000,'05398475612',750,'CONFIRMED',20000),
       ('64382857496','Sıla','Kaya',2000,'05435478456',500,'CONFIRMED',10000),
       ('74329758788','Selin','Engin',7500,'05448759463',250,'UNCONFIRMED',0),
       ('43214323456','Murat','Gümülcine',6000,'05324321522',400,'UNCONFIRMED',0);





